/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminRedirectRouteImport } from './routes/_authenticated/admin.redirect'
import { Route as AuthenticatedAdminPenggunaRouteImport } from './routes/_authenticated/admin.pengguna'
import { Route as AuthenticatedAdminPengaturanRouteImport } from './routes/_authenticated/admin.pengaturan'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminLogRouteImport } from './routes/_authenticated/admin.log'
import { Route as AuthenticatedAdminKeamananRouteImport } from './routes/_authenticated/admin.keamanan'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin.blog.index'
import { Route as AuthenticatedAdminWebsiteHeaderRouteImport } from './routes/_authenticated/admin.website.header'
import { Route as AuthenticatedAdminWebsiteFooterRouteImport } from './routes/_authenticated/admin.website.footer'
import { Route as AuthenticatedAdminBlogNewRouteImport } from './routes/_authenticated/admin.blog.new'
import { Route as AuthenticatedAdminBlogKategoriRouteImport } from './routes/_authenticated/admin.blog.kategori'
import { Route as AuthenticatedAdminBlogHeroRouteImport } from './routes/_authenticated/admin.blog.hero'
import { Route as AuthenticatedAdminBlogIdRouteImport } from './routes/_authenticated/admin.blog.$id'
import { Route as AuthenticatedAdminWebsiteHomepageIndexRouteImport } from './routes/_authenticated/admin.website.homepage.index'
import { Route as AuthenticatedAdminWebsiteHomepageSectionRouteImport } from './routes/_authenticated/admin.website.homepage.$section'
import { Route as AuthenticatedAdminBlogPreviewIdRouteImport } from './routes/_authenticated/admin.blog.preview.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRedirectRoute =
  AuthenticatedAdminRedirectRouteImport.update({
    id: '/redirect',
    path: '/redirect',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPenggunaRoute =
  AuthenticatedAdminPenggunaRouteImport.update({
    id: '/pengguna',
    path: '/pengguna',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPengaturanRoute =
  AuthenticatedAdminPengaturanRouteImport.update({
    id: '/pengaturan',
    path: '/pengaturan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLogRoute = AuthenticatedAdminLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKeamananRoute =
  AuthenticatedAdminKeamananRouteImport.update({
    id: '/keamanan',
    path: '/keamanan',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteHeaderRoute =
  AuthenticatedAdminWebsiteHeaderRouteImport.update({
    id: '/website/header',
    path: '/website/header',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteFooterRoute =
  AuthenticatedAdminWebsiteFooterRouteImport.update({
    id: '/website/footer',
    path: '/website/footer',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogNewRoute =
  AuthenticatedAdminBlogNewRouteImport.update({
    id: '/blog/new',
    path: '/blog/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogKategoriRoute =
  AuthenticatedAdminBlogKategoriRouteImport.update({
    id: '/blog/kategori',
    path: '/blog/kategori',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogHeroRoute =
  AuthenticatedAdminBlogHeroRouteImport.update({
    id: '/blog/hero',
    path: '/blog/hero',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogIdRoute =
  AuthenticatedAdminBlogIdRouteImport.update({
    id: '/blog/$id',
    path: '/blog/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteHomepageIndexRoute =
  AuthenticatedAdminWebsiteHomepageIndexRouteImport.update({
    id: '/website/homepage/',
    path: '/website/homepage/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteHomepageSectionRoute =
  AuthenticatedAdminWebsiteHomepageSectionRouteImport.update({
    id: '/website/homepage/$section',
    path: '/website/homepage/$section',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogPreviewIdRoute =
  AuthenticatedAdminBlogPreviewIdRouteImport.update({
    id: '/blog/preview/$id',
    path: '/blog/preview/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/keamanan': typeof AuthenticatedAdminKeamananRoute
  '/admin/log': typeof AuthenticatedAdminLogRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/admin/pengguna': typeof AuthenticatedAdminPenggunaRoute
  '/admin/redirect': typeof AuthenticatedAdminRedirectRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/hero': typeof AuthenticatedAdminBlogHeroRoute
  '/admin/blog/kategori': typeof AuthenticatedAdminBlogKategoriRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/admin/website/footer': typeof AuthenticatedAdminWebsiteFooterRoute
  '/admin/website/header': typeof AuthenticatedAdminWebsiteHeaderRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/blog/preview/$id': typeof AuthenticatedAdminBlogPreviewIdRoute
  '/admin/website/homepage/$section': typeof AuthenticatedAdminWebsiteHomepageSectionRoute
  '/admin/website/homepage/': typeof AuthenticatedAdminWebsiteHomepageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/admin/keamanan': typeof AuthenticatedAdminKeamananRoute
  '/admin/log': typeof AuthenticatedAdminLogRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/admin/pengguna': typeof AuthenticatedAdminPenggunaRoute
  '/admin/redirect': typeof AuthenticatedAdminRedirectRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/hero': typeof AuthenticatedAdminBlogHeroRoute
  '/admin/blog/kategori': typeof AuthenticatedAdminBlogKategoriRoute
  '/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/admin/website/footer': typeof AuthenticatedAdminWebsiteFooterRoute
  '/admin/website/header': typeof AuthenticatedAdminWebsiteHeaderRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/blog/preview/$id': typeof AuthenticatedAdminBlogPreviewIdRoute
  '/admin/website/homepage/$section': typeof AuthenticatedAdminWebsiteHomepageSectionRoute
  '/admin/website/homepage': typeof AuthenticatedAdminWebsiteHomepageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/keamanan': typeof AuthenticatedAdminKeamananRoute
  '/_authenticated/admin/log': typeof AuthenticatedAdminLogRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/pengaturan': typeof AuthenticatedAdminPengaturanRoute
  '/_authenticated/admin/pengguna': typeof AuthenticatedAdminPenggunaRoute
  '/_authenticated/admin/redirect': typeof AuthenticatedAdminRedirectRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/_authenticated/admin/blog/hero': typeof AuthenticatedAdminBlogHeroRoute
  '/_authenticated/admin/blog/kategori': typeof AuthenticatedAdminBlogKategoriRoute
  '/_authenticated/admin/blog/new': typeof AuthenticatedAdminBlogNewRoute
  '/_authenticated/admin/website/footer': typeof AuthenticatedAdminWebsiteFooterRoute
  '/_authenticated/admin/website/header': typeof AuthenticatedAdminWebsiteHeaderRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/_authenticated/admin/blog/preview/$id': typeof AuthenticatedAdminBlogPreviewIdRoute
  '/_authenticated/admin/website/homepage/$section': typeof AuthenticatedAdminWebsiteHomepageSectionRoute
  '/_authenticated/admin/website/homepage/': typeof AuthenticatedAdminWebsiteHomepageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/blog/$slug'
    | '/blog/'
    | '/admin/keamanan'
    | '/admin/log'
    | '/admin/media'
    | '/admin/pengaturan'
    | '/admin/pengguna'
    | '/admin/redirect'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/blog/hero'
    | '/admin/blog/kategori'
    | '/admin/blog/new'
    | '/admin/website/footer'
    | '/admin/website/header'
    | '/admin/blog/'
    | '/admin/blog/preview/$id'
    | '/admin/website/homepage/$section'
    | '/admin/website/homepage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/blog'
    | '/admin/keamanan'
    | '/admin/log'
    | '/admin/media'
    | '/admin/pengaturan'
    | '/admin/pengguna'
    | '/admin/redirect'
    | '/admin/roles'
    | '/admin/seo'
    | '/admin'
    | '/admin/blog/$id'
    | '/admin/blog/hero'
    | '/admin/blog/kategori'
    | '/admin/blog/new'
    | '/admin/website/footer'
    | '/admin/website/header'
    | '/admin/blog'
    | '/admin/blog/preview/$id'
    | '/admin/website/homepage/$section'
    | '/admin/website/homepage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/blog/'
    | '/_authenticated/admin/keamanan'
    | '/_authenticated/admin/log'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/pengaturan'
    | '/_authenticated/admin/pengguna'
    | '/_authenticated/admin/redirect'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/blog/$id'
    | '/_authenticated/admin/blog/hero'
    | '/_authenticated/admin/blog/kategori'
    | '/_authenticated/admin/blog/new'
    | '/_authenticated/admin/website/footer'
    | '/_authenticated/admin/website/header'
    | '/_authenticated/admin/blog/'
    | '/_authenticated/admin/blog/preview/$id'
    | '/_authenticated/admin/website/homepage/$section'
    | '/_authenticated/admin/website/homepage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/redirect': {
      id: '/_authenticated/admin/redirect'
      path: '/redirect'
      fullPath: '/admin/redirect'
      preLoaderRoute: typeof AuthenticatedAdminRedirectRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pengguna': {
      id: '/_authenticated/admin/pengguna'
      path: '/pengguna'
      fullPath: '/admin/pengguna'
      preLoaderRoute: typeof AuthenticatedAdminPenggunaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pengaturan': {
      id: '/_authenticated/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AuthenticatedAdminPengaturanRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/log': {
      id: '/_authenticated/admin/log'
      path: '/log'
      fullPath: '/admin/log'
      preLoaderRoute: typeof AuthenticatedAdminLogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/keamanan': {
      id: '/_authenticated/admin/keamanan'
      path: '/keamanan'
      fullPath: '/admin/keamanan'
      preLoaderRoute: typeof AuthenticatedAdminKeamananRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/header': {
      id: '/_authenticated/admin/website/header'
      path: '/website/header'
      fullPath: '/admin/website/header'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteHeaderRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/footer': {
      id: '/_authenticated/admin/website/footer'
      path: '/website/footer'
      fullPath: '/admin/website/footer'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteFooterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/new': {
      id: '/_authenticated/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AuthenticatedAdminBlogNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/kategori': {
      id: '/_authenticated/admin/blog/kategori'
      path: '/blog/kategori'
      fullPath: '/admin/blog/kategori'
      preLoaderRoute: typeof AuthenticatedAdminBlogKategoriRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/hero': {
      id: '/_authenticated/admin/blog/hero'
      path: '/blog/hero'
      fullPath: '/admin/blog/hero'
      preLoaderRoute: typeof AuthenticatedAdminBlogHeroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/$id': {
      id: '/_authenticated/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/homepage/': {
      id: '/_authenticated/admin/website/homepage/'
      path: '/website/homepage'
      fullPath: '/admin/website/homepage/'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteHomepageIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/homepage/$section': {
      id: '/_authenticated/admin/website/homepage/$section'
      path: '/website/homepage/$section'
      fullPath: '/admin/website/homepage/$section'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteHomepageSectionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/preview/$id': {
      id: '/_authenticated/admin/blog/preview/$id'
      path: '/blog/preview/$id'
      fullPath: '/admin/blog/preview/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogPreviewIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminKeamananRoute: typeof AuthenticatedAdminKeamananRoute
  AuthenticatedAdminLogRoute: typeof AuthenticatedAdminLogRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminPengaturanRoute: typeof AuthenticatedAdminPengaturanRoute
  AuthenticatedAdminPenggunaRoute: typeof AuthenticatedAdminPenggunaRoute
  AuthenticatedAdminRedirectRoute: typeof AuthenticatedAdminRedirectRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBlogIdRoute: typeof AuthenticatedAdminBlogIdRoute
  AuthenticatedAdminBlogHeroRoute: typeof AuthenticatedAdminBlogHeroRoute
  AuthenticatedAdminBlogKategoriRoute: typeof AuthenticatedAdminBlogKategoriRoute
  AuthenticatedAdminBlogNewRoute: typeof AuthenticatedAdminBlogNewRoute
  AuthenticatedAdminWebsiteFooterRoute: typeof AuthenticatedAdminWebsiteFooterRoute
  AuthenticatedAdminWebsiteHeaderRoute: typeof AuthenticatedAdminWebsiteHeaderRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
  AuthenticatedAdminBlogPreviewIdRoute: typeof AuthenticatedAdminBlogPreviewIdRoute
  AuthenticatedAdminWebsiteHomepageSectionRoute: typeof AuthenticatedAdminWebsiteHomepageSectionRoute
  AuthenticatedAdminWebsiteHomepageIndexRoute: typeof AuthenticatedAdminWebsiteHomepageIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminKeamananRoute: AuthenticatedAdminKeamananRoute,
  AuthenticatedAdminLogRoute: AuthenticatedAdminLogRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminPengaturanRoute: AuthenticatedAdminPengaturanRoute,
  AuthenticatedAdminPenggunaRoute: AuthenticatedAdminPenggunaRoute,
  AuthenticatedAdminRedirectRoute: AuthenticatedAdminRedirectRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBlogIdRoute: AuthenticatedAdminBlogIdRoute,
  AuthenticatedAdminBlogHeroRoute: AuthenticatedAdminBlogHeroRoute,
  AuthenticatedAdminBlogKategoriRoute: AuthenticatedAdminBlogKategoriRoute,
  AuthenticatedAdminBlogNewRoute: AuthenticatedAdminBlogNewRoute,
  AuthenticatedAdminWebsiteFooterRoute: AuthenticatedAdminWebsiteFooterRoute,
  AuthenticatedAdminWebsiteHeaderRoute: AuthenticatedAdminWebsiteHeaderRoute,
  AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
  AuthenticatedAdminBlogPreviewIdRoute: AuthenticatedAdminBlogPreviewIdRoute,
  AuthenticatedAdminWebsiteHomepageSectionRoute:
    AuthenticatedAdminWebsiteHomepageSectionRoute,
  AuthenticatedAdminWebsiteHomepageIndexRoute:
    AuthenticatedAdminWebsiteHomepageIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
